//! Regenerate test fixtures on demand.
//!
//! Run:
//!   cargo test --test build_fixtures -- --ignored
//!
//! Each `#[test] #[ignore]` writes one fixture to tests/fixtures/<name>.json.
//! The `build_all` test regenerates every fixture in a single run.
//!
//! Notes:
//! - `tests/fixtures/tiny.json.gz` is a real samply profile of `rustfmt --version`.
//!   Regenerated by `build_tiny` (requires `samply` and `rustfmt` on PATH).
//!   `libs[].path` and `libs[].debugPath` are nulled so symbolication is a
//!   deterministic no-op across machines (otherwise the recorder's local
//!   binaries would resolve to extra symbols and break snapshots elsewhere).
//!   Sample counts and frame addresses still vary per run, so snapshots
//!   under `tests/snapshots/` must be re-accepted after regeneration via
//!   `cargo insta accept`.
//! - `tests/fixtures/tiny_program.c` is C source for an e2e test, not a JSON fixture.
//! - `minimal_profile.json` and `source_attribution.json` are inlined JSON literals
//!   because fxprof's `Frame::Label` doesn't carry source info, and minimal has no
//!   samples so there's no benefit to generating it programmatically.

#[path = "helpers/mod.rs"]
mod helpers;

use helpers::synthetic::{SampleSpec, build_simple_profile};
use std::fs;

const FIXTURES_DIR: &str = "tests/fixtures";

fn write_fixture(name: &str, contents: &str) {
    let path = format!("{}/{}", FIXTURES_DIR, name);
    fs::write(&path, contents).unwrap_or_else(|e| panic!("writing {}: {}", path, e));
    eprintln!("wrote {}", path);
}

#[test]
#[ignore]
fn build_minimal_profile() {
    // Empty tables, single thread "Main" tid=1 pid=1.
    // Hand-authored: no samples to generate programmatically.
    let json = r#"{
    "meta": {"interval": 1.0, "startTime": 0.0, "product": "test"},
    "libs": [],
    "threads": [{
        "name": "Main",
        "tid": 1,
        "pid": 1,
        "registerTime": 0.0,
        "stringArray": ["foo", "bar"],
        "frameTable": {"length": 0, "address": [], "func": [], "category": [], "subcategory": [], "innerWindowID": [], "implementation": [], "line": [], "column": [], "nativeSymbol": []},
        "stackTable": {"length": 0, "frame": [], "category": [], "subcategory": [], "prefix": []},
        "samples": {"length": 0, "stack": [], "time": [], "weight": null, "weightType": "samples"},
        "funcTable": {"length": 0, "name": [], "isJS": [], "relevantForJS": [], "resource": [], "fileName": [], "lineNumber": [], "columnNumber": []},
        "resourceTable": {"length": 0, "lib": [], "name": [], "host": [], "type": []},
        "markers": {"length": 0, "data": [], "name": [], "startTime": [], "endTime": [], "phase": [], "category": []},
        "nativeSymbols": {"length": 0, "libIndex": [], "address": [], "name": [], "functionSize": []},
        "processType": "default",
        "processStartupTime": 0.0
    }]
}"#;
    write_fixture("minimal_profile.json", json);
}

#[test]
#[ignore]
fn build_two_functions() {
    let json = build_simple_profile(
        "two_functions",
        &[
            SampleSpec {
                stack: &[("hot", "")],
                count: 90,
            },
            SampleSpec {
                stack: &[("cold", "")],
                count: 10,
            },
        ],
    );
    write_fixture("two_functions.json", &json);
}

#[test]
#[ignore]
fn build_linear_chain() {
    let json = build_simple_profile(
        "linear_chain",
        &[SampleSpec {
            stack: &[("a", ""), ("b", ""), ("c", ""), ("d", "")],
            count: 100,
        }],
    );
    write_fixture("linear_chain.json", &json);
}

#[test]
#[ignore]
fn build_paths_to() {
    let json = build_simple_profile(
        "paths_to",
        &[
            SampleSpec {
                stack: &[("a", ""), ("b", ""), ("lock_acquire", "")],
                count: 50,
            },
            SampleSpec {
                stack: &[("a", ""), ("c", ""), ("work", "")],
                count: 50,
            },
        ],
    );
    write_fixture("paths_to.json", &json);
}

#[test]
#[ignore]
fn build_stacks_containing() {
    let json = build_simple_profile(
        "stacks_containing",
        &[
            SampleSpec {
                stack: &[("main", ""), ("do_work", ""), ("alloc_buf", "")],
                count: 10,
            },
            SampleSpec {
                stack: &[("main", ""), ("do_work", ""), ("alloc_str", "")],
                count: 10,
            },
            SampleSpec {
                stack: &[("main", ""), ("do_work", ""), ("compute", "")],
                count: 10,
            },
        ],
    );
    write_fixture("stacks_containing.json", &json);
}

#[test]
#[ignore]
fn build_source_attribution() {
    // Hand-authored JSON with per-frame line numbers.
    // fxprof's Frame::Label doesn't carry source info, so we inline the JSON directly.
    // Function "process_request" in "src/server.rs": 20 samples, 10 on line 3 and 10 on line 4.
    let json = r#"{
  "meta": {
    "interval": 1.0,
    "startTime": 0.0,
    "product": "test"
  },
  "libs": [],
  "threads": [
    {
      "name": "Main",
      "tid": 1,
      "pid": 1,
      "registerTime": 0.0,
      "stringArray": [
        "process_request",
        "src/server.rs"
      ],
      "frameTable": {
        "length": 2,
        "address": [
          -1,
          -1
        ],
        "func": [
          0,
          0
        ],
        "category": [
          null,
          null
        ],
        "subcategory": [
          null,
          null
        ],
        "innerWindowID": [
          null,
          null
        ],
        "implementation": [
          null,
          null
        ],
        "line": [
          3,
          4
        ],
        "column": [
          null,
          null
        ],
        "nativeSymbol": [
          null,
          null
        ]
      },
      "stackTable": {
        "length": 2,
        "frame": [
          0,
          1
        ],
        "category": [
          0,
          0
        ],
        "subcategory": [
          0,
          0
        ],
        "prefix": [
          null,
          null
        ]
      },
      "samples": {
        "length": 20,
        "stack": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "time": [
          0.0,
          1.0,
          2.0,
          3.0,
          4.0,
          5.0,
          6.0,
          7.0,
          8.0,
          9.0,
          10.0,
          11.0,
          12.0,
          13.0,
          14.0,
          15.0,
          16.0,
          17.0,
          18.0,
          19.0
        ],
        "weight": null,
        "weightType": "samples"
      },
      "funcTable": {
        "length": 1,
        "name": [
          0
        ],
        "isJS": [
          false
        ],
        "relevantForJS": [
          false
        ],
        "resource": [
          -1
        ],
        "fileName": [
          1
        ],
        "lineNumber": [
          null
        ],
        "columnNumber": [
          null
        ]
      },
      "resourceTable": {
        "length": 0,
        "lib": [],
        "name": [],
        "host": [],
        "type": []
      },
      "markers": {
        "length": 0,
        "data": [],
        "name": [],
        "startTime": [],
        "endTime": [],
        "phase": [],
        "category": []
      },
      "nativeSymbols": {
        "length": 0,
        "libIndex": [],
        "address": [],
        "name": [],
        "functionSize": []
      },
      "processType": "default",
      "processStartupTime": 0.0
    }
  ]
}"#;
    write_fixture("source_attribution.json", json);
}

/// Record `rustfmt --version` under samply, scrub local binary paths from the
/// resulting profile, and write it to `tests/fixtures/tiny.json.gz`.
///
/// Requires `samply` and `rustfmt` on PATH. Sample counts and frame addresses
/// vary per run; re-accept snapshots with `cargo insta accept` afterward.
///
/// **Opt-in via `REGENERATE_FIXTURES=1`.** This test rewrites a checked-in
/// fixture, which would invalidate the committed insta snapshots if it ran
/// alongside them in CI under `--include-ignored`. Run manually only when
/// you actually want to refresh the fixture.
///
/// Excluded from `build_all` because it shells out and depends on host tools.
#[test]
#[ignore]
fn build_tiny() {
    use flate2::{Compression, read::GzDecoder, write::GzEncoder};
    use std::io::{Read, Write};
    use std::process::Command;

    if std::env::var("REGENERATE_FIXTURES").is_err() {
        eprintln!(
            "skipping build_tiny: set REGENERATE_FIXTURES=1 to regenerate \
             tests/fixtures/tiny.json.gz (note: invalidates insta snapshots)"
        );
        return;
    }

    let tmp = tempfile::Builder::new()
        .suffix(".json.gz")
        .tempfile()
        .expect("tempfile");
    let status = Command::new("samply")
        .args(["record", "--save-only", "--no-open", "-o"])
        .arg(tmp.path())
        .args(["--", "rustfmt", "--version"])
        .status()
        .expect("running samply (is it on PATH?)");
    assert!(status.success(), "samply record exited with {status}");

    let mut raw = Vec::new();
    GzDecoder::new(fs::File::open(tmp.path()).unwrap())
        .read_to_end(&mut raw)
        .unwrap();
    let mut profile: serde_json::Value = serde_json::from_slice(&raw).unwrap();

    // Strip local-machine paths so symbolication is a deterministic no-op
    // across machines. See module-level docs.
    if let Some(libs) = profile.get_mut("libs").and_then(|v| v.as_array_mut()) {
        for lib in libs {
            if let Some(o) = lib.as_object_mut() {
                o.insert("path".into(), serde_json::Value::Null);
                o.insert("debugPath".into(), serde_json::Value::Null);
            }
        }
    }

    let path = format!("{}/tiny.json.gz", FIXTURES_DIR);
    let f = fs::File::create(&path).unwrap();
    let mut gz = GzEncoder::new(f, Compression::default());
    gz.write_all(&serde_json::to_vec(&profile).unwrap())
        .unwrap();
    gz.finish().unwrap();
    eprintln!("wrote {}", path);
}

/// Regenerate all synthetic fixtures in one run. Excludes `build_tiny`.
///
/// Equivalent to: `cargo test --test build_fixtures -- --ignored`
#[test]
#[ignore]
fn build_all() {
    build_minimal_profile();
    build_two_functions();
    build_linear_chain();
    build_paths_to();
    build_stacks_containing();
    build_source_attribution();
}
